# Generated by Django 2.2 on 2019-05-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190522_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='icon',
            field=models.ImageField(height_field=400, upload_to='media/', width_field=400),
        ),
    ]
