# Generated by Django 2.2 on 2019-05-22 06:57

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.IntegerField()),
                ('content', models.CharField(max_length=100)),
                ('dp_abb', models.CharField(max_length=100)),
                ('sb_index', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('tag_name', djongo.models.fields.ListField(verbose_name=models.CharField(max_length=100))),
                ('tag_count', djongo.models.fields.ListField(verbose_name=models.IntegerField())),
                ('post_date', models.DateTimeField()),
                ('revise_date', models.DateField()),
                ('good_count', models.IntegerField()),
                ('bad_count', models.IntegerField()),
                ('author', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.IntegerField()),
                ('content', models.CharField(max_length=100)),
                ('article_id', models.IntegerField()),
                ('post_date', models.DateField()),
                ('revise_date', models.DateField()),
                ('good_count', models.IntegerField()),
                ('bad_count', models.IntegerField()),
                ('author', models.CharField(max_length=100)),
                ('child_comment_id', models.IntegerField()),
                ('parent_comment_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp_name', models.CharField(max_length=100)),
                ('dp_abb', models.CharField(max_length=100)),
                ('sb_name', djongo.models.fields.ListField(verbose_name=models.CharField(max_length=100))),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp_name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
                ('subjects', djongo.models.fields.ListField(verbose_name=models.CharField(max_length=100))),
            ],
        ),
    ]
