# Generated by Django 2.2 on 2019-05-31 09:58

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100000)),
                ('dp_abb', models.CharField(max_length=100)),
                ('sb_index', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('tag_name', djongo.models.fields.ListField(verbose_name=models.CharField(max_length=100))),
                ('tag_count', djongo.models.fields.ListField(verbose_name=models.IntegerField())),
                ('post_date', models.DateField()),
                ('revise_date', models.DateField()),
                ('good_list', djongo.models.fields.ListField(verbose_name=models.CharField(max_length=100))),
                ('bad_list', djongo.models.fields.ListField(verbose_name=models.CharField(max_length=100))),
                ('author', models.CharField(max_length=100)),
                ('top', models.BooleanField(default=False)),
                ('exist', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField()),
                ('child_comment_id', djongo.models.fields.ListField(default=[], verbose_name=models.IntegerField())),
                ('good_list', djongo.models.fields.ListField(default=[], verbose_name=models.CharField(max_length=100))),
                ('bad_list', djongo.models.fields.ListField(default=[], verbose_name=models.CharField(max_length=100))),
                ('content', models.CharField(max_length=100000)),
                ('post_date', models.DateField()),
                ('revise_date', models.DateField()),
                ('author', models.CharField(max_length=100)),
                ('parent_comment_id', models.IntegerField()),
                ('exist', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp_name', models.CharField(max_length=100)),
                ('dp_abb', models.CharField(max_length=100)),
                ('sb_name', djongo.models.fields.ListField(verbose_name=models.CharField(max_length=100))),
            ],
        ),
    ]
