# Generated by Django 2.2 on 2019-05-17 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Block',
        ),
    ]
